#ifndef INCLUDE_GLOBALS_H_
#define INCLUDE_GLOBALS_H_

#define XSMALL 1e5
#define EPSILON 1e-9
#define INF 1e9

#define BENDERS2P_PHASE2PERC 80
#define BENDERS2P_NODELIM 3
// #define BENDERSCALLBACK_RANDOMPERC 50
// #define BENDERSCALLBACK_NODELIM 6

#define HF_PERCENTAGE 80
#define HF_ITERATIONS 20
#define HF_INITIAL_PERC_TIME 0.1

#define SF_INITIAL_K 3
#define SF_MAX_K 15
#define SF_K_STEP 2
#define SF_INITIAL_PERC_TIME 0.2

#define GRASP_K 5

#define TWOOPT_NINITIALSOL 500

#define VNS_K_START 3
#define VNS_K_MAX 20
#define VNS_K_STEP 1

#define TS_MAX_TENURE 120
#define TS_MIN_TENURE 20
#define TS_PHASEDURATION 1000

#define GENETIC_N 1000
#define GENETIC_K 100
#define GENETIC_PERC_LUCKYCHILDREN 0.005
#define GENETIC_NBESTSOLS 200
#define GENETIC_NMUTATIONS 300
#define GENETIC_NMOVES 10
#define GENETIC_PERC_TIME 0.9

extern int VERBOSE;
extern int EXTRA_VERBOSE;
extern int CALLBACK_VERBOSE;
extern int GEN_NNODES;

extern int hook;

#endif  // INCLUDE_GLOBALS_H_
