#ifndef INCLUDE_GLOBALS_H_
#define INCLUDE_GLOBALS_H_

#define VERBOSE 0
#define SUPPRESS_CALLBACK 1
#define EXTRA 1

#define XSMALL 1e5
#define EPSILON 1e-9

#define NUM_NODES 30

#define HF_PERCENTAGE 80
#define HF_ITERATIONS 20
#define HF_INITIAL_FRACTION_TIME 10

#define SF_INITIAL_K 3
#define SF_MAX_K 15
#define SF_K_STEP 2
#define SF_INITIAL_FRACTION_TIME 5

#define GRASP_K 10
#define GRASP_MAX_ITERATION 1

#endif  // INCLUDE_GLOBALS_H_
